### ISSUE TITLE
Component package crash when logger is not activated

### ISSUE THREAD

**Issue by philippevk** [Hypercubed/autocmdr#19]
Hi!

Yesterday I used the generator-commander and I chose to only install the 'package' component. While trying to test my application I had an error message saying that program.log was not defined. Having no idea what program.log was supposed to be I had to spend quite some time figuring out what was happening before realizing that the 'logger' component was required.

I can think of three way this problem could be fixed:
1) Display a more helpful error message
2) Disable logging in the 'package' component when program.log is not defined
3) Force 'logger' component to be included

Thanks!

**Comment by Hypercubed** [comment]
I'm sorry, I've been neglecting this project and the generator.  They could both use a major update.  I've fixed this issue in v0.0.10 of generator-commander, it now includes the logger component if other components need it.

Thank you again, sorry for the 9month delay!!!
